MyRpg/MySite/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :quests do
    resources :steps, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  end

  get 'welcome' => 'pages#home'
end

MyRpg/MySite/app/models/quest.rb
class Quest < ApplicationRecord
    has_many :steps, dependent: :destroy
    validates :name, presence: true
    validates :description, presence: true
  end
  

MyRpg/MySite/app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  before_action :set_quest, only: [:show, :edit, :update, :destroy]

  def index
    @quests = Quest.all
  end

  def show
    @steps = @quest.steps
  end

  def new
    @quest = Quest.new
  end

  def edit
  end

  def create
    @quest = Quest.new(quest_params)

    if @quest.save
      redirect_to @quest, notice: 'Quest was successfully created.'
    else
      render :new
    end
  end

  def update
    if @quest.update(quest_params)
      redirect_to @quest, notice: 'Quest was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @quest.destroy
    redirect_to quests_url, notice: 'Quest was successfully destroyed.'
  end

  private

  def set_quest
    @quest = Quest.find(params[:id])
  end

  def quest_params
    params.require(:quest).permit(:name, :description)
  end
end

MyRpg/MySite/app/helpers/quests_helper.rb
module QuestsHelper
end

MyRpg/MySite/app/views/quests/_form.html.erb
<%= form_with(model: quest, local: true) do |form| %>
  <% if quest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quest.errors.count, "error") %> prohibited this quest from being saved:</h2>

      <ul>
        <% quest.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

MyRpg/MySite/app/views/quests/edit.html.erb
<h1>Edit Quest</h1>

<%= render 'form', quest: @quest %>

<%= link_to 'Back', quests_path %>

MyRpg/MySite/app/views/quests/index.html.erb
<h1>Quests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quests.each do |quest| %>
      <tr>
        <td><%= quest.name %></td>
        <td><%= quest.description %></td>
        <td><%= link_to 'Show', quest %></td>
        <td><%= link_to 'Edit', edit_quest_path(quest) %></td>
        <td><%= link_to 'Destroy', quest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Quest', new_quest_path %>

MyRpg/MySite/app/views/quests/new.html.erb
<h1>New Quest</h1>

<%= render 'form', quest: @quest %>

<%= link_to 'Back', quests_path %>

MyRpg/MySite/app/views/quests/show.html.erb
<h1>Quest Details</h1>

<p>
  <strong>Name:</strong>
  <%= @quest.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @quest.description %>
</p>

<h2>Steps</h2>
<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quest.steps.each do |step| %>
      <tr>
        <td><%= step.description %></td>
        <td><%= step.order %></td>
        <td><%= link_to 'Show', [@quest, step] %></td>
        <td><%= link_to 'Edit', edit_quest_step_path(@quest, step) %></td>
        <td><%= link_to 'Destroy', [@quest, step], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Step', new_quest_step_path(@quest) %> |
<%= link_to 'Back to Quests', quests_path %>